name: Test ACR Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo "${{ toJson(github) }}"
      - name: Print Secret Values
        run: |
          echo "ACR_REGISTRY=${{ secrets.ACR_REGISTRY }}"
          echo "ACR_USERNAME=${{ secrets.ACR_USERNAME }}"
          if [ -n "${{ secrets.ACR_PASSWORD }}" ]; then
            echo "ACR_PASSWORD Length=Set"
          else
            echo "ACR_PASSWORD Length=NotSet"
          fi
